### ISSUE TITLE
Searching finds HTML tags and displays them

### ISSUE THREAD

**Issue by RamouzK** [DiemenDesign/summernote-text-findnreplace#2]
This find and replace plugin seemed fine until I tested by typing only one letter "a" or "c", etc. It would display HTML tags.
I then realized that any word that matches an HTML tag would be displayed, such as "center" since I centered my text. I can't use this like this, too bad :( - I hope it can be fixed.

See screenshot below for an example:

![find-and-replace-bug](https://user-images.githubusercontent.com/48268798/53853875-444bb500-3f95-11e9-8252-752ae35c7e09.jpg)

**Comment by DennisSuitters** [comment]
Was able to fix this finally.
Sorry it took so long to see this issue, not sure why I never got a notification of your issue.
